language: c

compiler: gcc

git:
  depth: 1

matrix:
  include:
    - compiler: clang

script:
  - ./autogen.sh && ./configure && make

before_install:
  - sudo add-apt-repository --yes ppa:chewing/chewing
  - sudo apt-get update -qq
  - sudo apt-get install -qq intltool libchewing3-dev libglib2.0-dev libgtk-3-dev libltdl-dev libscim-dev libtool
